/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculadora;


import java.awt.event.KeyEvent;

/**
 *
 * @author Gustavo
 * 
 */
public class Calculadora extends javax.swing.JFrame {
/* Metodo para apagar apenas um caracter por vez,
 * ao precionar o botao "BackSpace"
 * 
 */
    void clear(String textt) {

        String texto = jVisor.getText(); // Obtendo o Texto do visor
        int tamanho = texto.length(); // obtendo em um inteiro o tamanho do texto
        if (texto.equals("")) {
            jVisor.setText("");
        } else {
            jVisor.setText(texto.substring(0, tamanho - 1)); 
        }


    }
/* metodo para transformar uma String em numero
 * 
 */
    static public long validaLong(String nu) {

        long a = Long.parseLong(nu);

        return a;

    }
/* Metodo responsavel para validar se a string tem . 
 * e fazer um cast para Double, 
 * 
 */
    static public double validaPonto(String n) {

        String num = String.valueOf(n.length());
        for (int i = 0; i < num.length(); i++) {
            if (num.equals(".")) {
                double a = Double.parseDouble(num);
            }
        }
        double a = Double.parseDouble(num);
        return a;

    }

    /**
     * Creates new form Calcu
     */
    public Calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSub = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButton0 = new javax.swing.JButton();
        jButtonIgual = new javax.swing.JButton();
        jButtonSoma = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButtonVezes = new javax.swing.JButton();
        jButtonDividir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jVisor = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setBounds(new java.awt.Rectangle(0, 0, 240, 300));
        setMinimumSize(new java.awt.Dimension(12, 24));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSub.setText("-");
        jButtonSub.setMaximumSize(new java.awt.Dimension(39, 23));
        jButtonSub.setMinimumSize(new java.awt.Dimension(39, 23));
        jButtonSub.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSub, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 41, 32));

        jButtonClear.setText("C");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, 30));

        jButton0.setText("0");
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton0, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        jButtonIgual.setText("=");
        jButtonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIgualActionPerformed(evt);
            }
        });
        jButtonIgual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonIgualKeyPressed(evt);
            }
        });
        getContentPane().add(jButtonIgual, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 42, 70));

        jButtonSoma.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButtonSoma.setText("+");
        jButtonSoma.setPreferredSize(new java.awt.Dimension(39, 22));
        jButtonSoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSomaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 40, 30));

        jButton8.setText("8");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jButton9.setText("9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jButton7.setText("7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jButton4.setText("4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        jButton5.setText("5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButtonVezes.setText("*");
        jButtonVezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVezesActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVezes, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 150, 40, 30));

        jButtonDividir.setText("/");
        jButtonDividir.setMaximumSize(new java.awt.Dimension(39, 23));
        jButtonDividir.setMinimumSize(new java.awt.Dimension(39, 23));
        jButtonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDividirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 39, 30));

        jButton3.setText("3");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jButton2.setText("2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jButton10.setText("CE");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 42, 43));

        jButton11.setText(".");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 39, 30));

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(100, 100));

        jVisor.setEditable(false);
        jVisor.setColumns(20);
        jVisor.setLineWrap(true);
        jVisor.setRows(5);
        jVisor.setTabSize(5);
        jVisor.setAutoscrolls(false);
        jVisor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jVisorKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jVisor);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 160, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "1");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton0ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + "0");
    }//GEN-LAST:event_jButton0ActionPerformed

    private void jButtonSomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSomaActionPerformed
        // TODO add your handling code here:

        String texto = jVisor.getText();

        jVisor.setText(texto + " + ");

    }//GEN-LAST:event_jButtonSomaActionPerformed

    private void jButtonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIgualActionPerformed
        // TODO add your handling code here:
/*
*Umas das partes mais legais que achei em desenvolver a calculadora, foi obter os numeros digitados e separalos, em um array
* e assim pode efetuar a operação correta, mas ainda esta faltando algo pois ainda só conseguimos, 
* fazer operações de 2 numeros Ex:  10 + 20  e assim obtendo o resultado, esperando ainda conseguir fazer
* 10 + 20 + 30 - 40 . etc
*/
        String tex = jVisor.getText();
        String text = String.valueOf(tex.length());
        String linhas[] = tex.split(" ");
        for (String a : linhas) {
        }
        //for(int a = 0; a < linhas.length;a++){
        //    if(linhas[a]!= " "){
        //      String numeros = linhas[a];
        //    System.out.println(numeros += numeros+linhas[a]);
        //}
        // }
        String num1 = linhas[0];
        String num2 = linhas[2];

        for (int i = 0; i < linhas.length; i++) {
            if (linhas[i].equals("+")) {
                long a = validaLong(num1);
                long b = validaLong(num2);
                long result = a + b;
                String res = String.valueOf(result);
                jVisor.setText(res);
            }

            if (linhas[i].equals("*")) {
                long a = validaLong(num1);
                long b = validaLong(num2);
                long result = a * b;
                String res = String.valueOf(result);
                jVisor.setText(res);
            }
            if (linhas[i].equals("-")) {
                long a = validaLong(num1);
                long b = validaLong(num2);
                long result = a - b;
                String res = String.valueOf(result);
                jVisor.setText(res);
            }
            if (linhas[i].equals("/")) {

                String num = String.valueOf(num1);
                String nume = String.valueOf(num2);
                double a = Double.parseDouble(num);
                double b = Double.parseDouble(nume);
                double result = a / b;
                String res = String.valueOf(result);
                jVisor.setText(res);

            }
        }

    }//GEN-LAST:event_jButtonIgualActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:

        jVisor.setText("");

    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed

        String texto = jVisor.getText();
        int tamanho = texto.length();
        if (texto.equals("")) {
            jVisor.setText("");
        } else {
            jVisor.setText(texto.substring(0, tamanho - 1));
        }

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDividirActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();

        jVisor.setText(texto + " / ");
    }//GEN-LAST:event_jButtonDividirActionPerformed

    private void jButtonVezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVezesActionPerformed
        // TODO add your handling code here:

        String texto = jVisor.getText();

        jVisor.setText(texto + " * ");

    }//GEN-LAST:event_jButtonVezesActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + ".");
    }//GEN-LAST:event_jButton11ActionPerformed

    

    private void jButtonSubActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubActionPerformed
        // TODO add your handling code here:
        String texto = jVisor.getText();
        jVisor.setText(texto + " - ");

    }//GEN-LAST:event_jButtonSubActionPerformed

    private void jVisorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jVisorKeyPressed
        // TODO add your handling code here:
        String text = jVisor.getText();
        if (evt.getExtendedKeyCode() == KeyEvent.VK_ADD) {
            String texto = jVisor.getText();
            jVisor.setText(texto + " + ");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_SUBTRACT) {
            String texto = jVisor.getText();
            jVisor.setText(texto + " - ");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_DIVIDE) {
            String texto = jVisor.getText();
            jVisor.setText(texto + " / ");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_MULTIPLY) {
            String texto = jVisor.getText();
            jVisor.setText(texto + " * ");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD1) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "1");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD0) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "0");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD2) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "2");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD3) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "3");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD4) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "4");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD5) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "5");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD6) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "6");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD7) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "7");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD8) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "8");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_NUMPAD9) {
            String texto = jVisor.getText();
            jVisor.setText(texto + "9");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_BACK_SPACE) {
            String texto = jVisor.getText();
            clear(texto);
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_DELETE) {

            jVisor.setText("");
        }
        if (evt.getExtendedKeyCode() == KeyEvent.VK_DECIMAL) {
            String texto = jVisor.getText();
            jVisor.setText(text + ".");
        }

        if (evt.getExtendedKeyCode() == KeyEvent.VK_ENTER) {
            /*
*Umas das partes mais legais que achei em desenvolver a calculadora, foi obter os numeros digitados e separalos, em um array
* e assim pode efetuar a operação correta, mas ainda esta faltando algo pois ainda só conseguimos, 
* fazer operações de 2 numeros Ex:  10 + 20  e assim obtendo o resultado, esperando ainda conseguir fazer
* 10 + 20 + 30 - 40 . etc
*/
            String tex = jVisor.getText();
            String textt = String.valueOf(tex.length());
            String linhas[] = tex.split(" ");
            for (String a : linhas) {
            }

            String num1 = linhas[0];
            String num2 = linhas[2];

            for (int i = 0; i < linhas.length; i++) {
                if (linhas[i].equals("+")) {
                    long a = validaLong(num1);
                    long b = validaLong(num2);

                    long result = a + b;
                    String res = String.valueOf(result);
                    jVisor.setText(res);
                }

                if (linhas[i].equals("*")) {
                    long a = validaLong(num1);
                    long b = validaLong(num2);
                    long result = a * b;
                    String res = String.valueOf(result);
                    jVisor.setText(res);
                }
                if (linhas[i].equals("-")) {
                    long a = validaLong(num1);
                    long b = validaLong(num2);
                    long result = a - b;
                    String res = String.valueOf(result);
                    jVisor.setText(res);
                }
                if (linhas[i].equals("/")) {

                    String num = String.valueOf(num1);
                    String nume = String.valueOf(num2);
                    double a = Double.parseDouble(num);
                    double b = Double.parseDouble(nume);

                    double result = a / b;

                    String res = String.valueOf(result);
                    jVisor.setText(res);

                }
            }
        }
    }//GEN-LAST:event_jVisorKeyPressed
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDividir;
    private javax.swing.JButton jButtonIgual;
    private javax.swing.JButton jButtonSoma;
    private javax.swing.JButton jButtonSub;
    private javax.swing.JButton jButtonVezes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jVisor;
    // End of variables declaration//GEN-END:variables
}
